apiVersion: apps/v1    # ← REQUIRED
kind: Deployment       # ← REQUIRED
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000